### ISSUE TITLE
import all in app.js ? like moon-cli ?

### ISSUE THREAD

**Issue by sadeghbarati** [diasfs/moonjs-loader#1]
in moon-cli compiler, must require all of the components with require in scripts.js
``` javascript
require("./components/header.moon")(Moon);
```
in webpack and moon-loader we can import them in aother components and import one file in scripts.js ?

your .moon example is
``` html 
{# File: index.moon #}
<p>{{title}}</p>
```

dont need 
``` html
<template>
  <p>{{title}}</p>
</template>
<style scope>
   p {
    color: red
  }
</style>

<script>
    export = {
     props: ["title"]
    }
</script>
```

**Comment by diasfs** [comment]
The moonjs-loader just transforms a html file into a function to use in the "render" option of the component or moon instance.

The moon-cli format will be suported in the future.
